@host = http://localhost:3000

###
GET {{host}}/api/teachers

###
POST {{host}}/api/teachers
Content-Type: application/json

{
  "fullName":"test",
  "department":"test department",
  "birthDate":20001129,
  "status":true,
  "userName":"test1",
  "passWord":"password"
}