@host = http://localhost:3000

###
GET {{host}}/api/teachers

###
POST {{host}}/api/teachers
Content-Type: application/json

{
  "fullName":"test7",
  "department":"test7 department",
  "birthDate":888888888,
  "status":true,
  "userName":"test7",
  "passWord":"password7",
  "isCoord": true
}

###
DELETE {{host}}/api/teachers/6451a76a278b33981ffb39c6

###
GET {{host}}/api/groups

###
POST {{host}}/api/groups
Content-Type: application/json

{
  "group":"groupTest2",
  "department":"test2 department",
  "status":true,
  "students":["getjRpBcKfH9vvRF4r4Kg","RYKuhzcn9WsKHa_TRW5Hj","J81e73UlFmVOBuFlcBmOr"],
  "professor":"64519476ddfcc66bd7ee92fd"
}

###
GET {{host}}/api/students

###
POST {{host}}/api/students
Content-Type: application/json

{
  "fullName":"test6 Student",
  "email":"email6@iteso.mx",
  "carreer": "Carrera1"
}


###
GET {{host}}/api/asignaturas

###
GET {{host}}/api/asignaturas/PRG001

###
POST {{host}}/api/asignaturas
Content-Type: application/json

{
  "codigo": "mat005",
  "nombre": "Ecuaciones Diferenciales",
  "creditos": 8,
  "depto": "DFM",
  "descripcion": "Curso de ecuaciones diferenciales para carreras de ingenieria",
  "areaAsig": "Saberes profesionales",
  "grupos": []
}

###
PUT {{host}}/api/asignaturas/MAT005
Content-Type: application/json

{
  "nombre": "Ecuaciones Diferenciales",
  "creditos": 8,
  "depto": "DMF",
  "descripcion": "Curso de ecuaciones diferenciales para carreras de ingenieria con temas especializados en el area",
  "areaAsig": "Saberes profesionales",
  "grupos": []
}

###
DELETE  {{host}}/api/asignaturas/mat002


  