@host = http://localhost:3000

###
GET {{host}}/api/teachers

###
POST {{host}}/api/teachers
Content-Type: application/json

{
  "fullName":"test6",
  "department":"test2 department",
  "birthDate":20001129,
  "status":true,
  "userName":"test6",
  "passWord":"password"
}

###
DELETE {{host}}/api/teachers/6451a76a278b33981ffb39c6

###
GET {{host}}/api/groups

###
POST {{host}}/api/groups
Content-Type: application/json

{
  "group":"groupTest2",
  "department":"test2 department",
  "status":true,
  "students":["getjRpBcKfH9vvRF4r4Kg","RYKuhzcn9WsKHa_TRW5Hj","J81e73UlFmVOBuFlcBmOr"],
  "professor":"64519476ddfcc66bd7ee92fd"
}

###
GET {{host}}/api/students

###
POST {{host}}/api/students
Content-Type: application/json

{
  "fullName":"test6 Student",
  "email":"email6@iteso.mx",
  "carreer": "Carrera1"
}


###
GET {{host}}/api/asignaturas

###
GET {{host}}/api/asignaturas/CHS001

###
POST {{host}}/api/asignaturas
Content-Type: application/json

{
  "codigo": "CRR005",
  "nombre": "Contexto Historico-social",
  "creditos": 8,
  "depto": "CRU",
  "descripcion": "Curso donde se analizara el contexto historico-social de la epoca actual",
  "areaAsig": "Curriculum institucional",
  "grupos": ["Dx06En-h4_az8PwZwgW1b"]
}

###
PUT {{host}}/api/asignaturas/MAT005
Content-Type: application/json

{
  "nombre": "Ecuaciones Diferenciales",
  "creditos": 8,
  "depto": "DMF",
  "descripcion": "Curso de ecuaciones diferenciales para carreras de ingenieria con temas especializados en el area",
  "areaAsig": "Saberes profesionales",
  "grupos": ["Dx06En-h4_az8PwZwgW1b"]
}

###
DELETE  {{host}}/api/asignaturas/CRR005
